title: Sencilla
author:
  name: Jane Doe
  email: janedoe@example.com
description: >-
  A Jekyll theme for blogs and portfolio websites.

url: ""

permalink: /:categories/:title/

# Move your logo to "/assets/img"
profile_picture: "/assets/img/profile-picture.jpg"

# Move your logo to "/assets/img" and rename it as "site-logo". Comment if you don't want to add a site logo.
logo: "/assets/img/site-logo"

# Social Links will appear under the "Contact" link in the top navigation bar.
## Uncomment the lines for which you want to add the social links.
## Can't see your favorite social media platform? Please write me an email.
github: dyskun/sencilla
#linkedin: 
#twitter: 
#facebook:
#instagram:

date_format: "%b %-d, %Y"

# Do you want to add a script between the <head> </head> tags? 
# Make a directory in the root of your site: /_includes
# Create a file named custom-head.html in the _includes directory
# Paste the script you want to add in custom-head.html
# Replace false with true to activate your script
custom_head: true

# "Subscribe to the RSS feed" text in the bottom panel.
# true to show. false to hide.
subscribe: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
